name: Run Tests

on:
  push:
    branches:
      - main
      - alpha

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          package_json_file: package.json

      - name: Debug workflow run
        run : |
          echo "Workflow: ${{ github.workflow }}"
          echo "Workflow Run Job: ${{ github.job }}"
          echo "Workflow Run Ref: ${{ github.ref }}"
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        run: pnpm run test
        working-directory: apps/server

  notify-release:
    name: Notify Release
    needs: unit-tests
    if: ${{ needs.unit-tests.result == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Trigger Release Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Release
    
